SELECT 
	T1.Descr AS DESCRICAO,
	CASE T2.KeyFld_1_V  
		WHEN 100 THEN 'REV_CONTRIBUINTE' 
		WHEN 102 THEN 'CONTRIBUINTE'
		WHEN 104 THEN 'NAO_CONTRIBUINTE'
		WHEN 115 THEN 'PESSOA FISICA'

	END GRUPO_CLIENTE,
	
	CASE T2.KeyFld_2_V
		WHEN 1 THEN 00
		WHEN 2 THEN 60
		WHEN 3 THEN 20
		WHEN 4 THEN 41
		WHEN 5 THEN 90
	END GRUPO_MATERIAL, 
	

	T2.KeyFld_3_V AS UF,
	 
	CASE T5.UsageCode
		 WHEN 10 THEN 'REVENDA'
		 WHEN 12 THEN 'BONIFICAÇÃO'
		 WHEN 16 THEN 'DOAÇÃO' 
    END UTILIZACAO,

	T5.TAXCODE AS COD_IMP



FROM TCD1 T1
	INNER JOIN TCD2 T2 ON T2.Tcd1Id = T1.AbsId
	INNER JOIN TCD3 T3 ON T2.AbsID = T3.Tcd2Id
	--INNER JOIN TCD4 T4 ON T4.Tcd2Id = T2.AbsId
	INNER JOIN TCD5 T5 ON T5.Tcd3Id = T3.Tcd2Id
						

WHERE T1.KeyFld_1 = 11
	  AND T1.KeyFld_2 = 3
	  AND T5.UsageCode IN (10,12,16)
	 -- AND T2.KeyFld_1_V = 102gbb82
	  AND T5.TAXCODE IS NOT NULL

ORDER BY T2.KeyFld_1_V,T2.KeyFld_2_V,T2.KeyFld_3_V