SELECT 
	ITEMCODE AS 'Codigo Item'
   ,ITEMNAME AS 'NOME'
   ,FrgnName AS 'ABREVIÇÃO DO ITEM'
   ,CAST(OnHand AS DECIMAL)AS 'EM ESTOQUE'
   ,CAST (IsCommited AS DECIMAL) AS 'CONFIRMADO PARA SAIR'
   ,CAST (OnHand - IsCommited AS DECIMAL) AS 'DISPONIVEL'
FROM OITM
WHERE ITEMCODE LIKE 'M%'